RestApiClient/Models/Entities/Language.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace RestApiClient.Models
{
    public class Language
    {
        /// <summary>
        /// Id
        /// </summary> 
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Название
        /// </summary>    
        [Required]
        [Display(Name = "Название", Order = 5)]
        public string Name { get; set; }

        /// <summary>
        /// Список книг
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual ICollection<Book> Books { get; set; }
    }
}

RestApiClient/Controllers/LanguagesController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using RestApiClient.Models;

namespace RestApiClient.Controllers
{
    public class LanguagesController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var db = new LibraryContext();
            var languages = db.Languages.ToList();

            return View(languages);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var language = new Language();
            return View(language);
        }

        [HttpPost]
        public ActionResult Create(Language model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new LibraryContext();                      

            db.Languages.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Languages/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new LibraryContext();
            var language = db.Languages.FirstOrDefault(x => x.Id == id);
            if (language == null)
                return RedirectPermanent("/Languages/Index");

            db.Languages.Remove(language);
            db.SaveChanges();

            return RedirectPermanent("/Languages/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new LibraryContext();
            var language = db.Languages.FirstOrDefault(x => x.Id == id);
            if (language == null)
                return RedirectPermanent("/Languages/Index");

            return View(language);
        }

        [HttpPost]
        public ActionResult Edit(Language model)
        {
            var db = new LibraryContext();
            var language = db.Languages.FirstOrDefault(x => x.Id == model.Id);
            if (language == null)
                ModelState.AddModelError("Id", "Жанр не найден");

            if (!ModelState.IsValid)
                return View(model);

            MappingLanguage(model, language);

            db.Entry(language).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Languages/Index");
        }

        private void MappingLanguage(Language sourse, Language destination)
        {
            destination.Name = sourse.Name;
        }
    }
}

RestApiClient/Views/Languages/Create.cshtml
@using RestApiClient.Models
@model Language

<h3>Язык</h3>

@using (Html.BeginForm("Create", "Languages", FormMethod.Post))
{
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" class="btn btn-primary" />
    @Html.ActionLink("Отменить", "Index", "Languages", null, new { @class = "btn btn-danger" })
}

RestApiClient/Views/Languages/Edit.cshtml
@using RestApiClient.Models
@model Language

<h3>Язык</h3>

@using (Html.BeginForm("Edit", "Languages", FormMethod.Post))
{
    @Html.ValidationSummary()
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" class="btn btn-primary" />
    @Html.ActionLink("Отменить", "Index", "Languages", null, new { @class = "btn btn-danger" })
}

RestApiClient/Views/Languages/Index.cshtml
@using RestApiClient.Models
@model List<Language>
@{
    string controllerName = "Languages";
}
<h3>Языки</h3>

@Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-primary" })

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>
                Название
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var entity in Model)
        {
            <tr>
                <td>
                    @entity.Name
                </td>
                <td class="grid-cell-action">
                    <div class="btn-group mb-3">
                        <a href="/@controllerName/Edit/@entity.Id" class="btn btn-outline-secondary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                            </svg>
                        </a>
                        <a href="/@controllerName/Delete/@entity.Id" class="btn btn-outline-secondary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"></path>
                            </svg>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>