RestApiClient/Controllers/BooksController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using RestApiClient.Models;

namespace RestApiClient.Controllers
{
    public class BooksController : Controller
    {
        private readonly string _key = "123456Qq";

        [HttpGet]
        public ActionResult Index()
        {
            var db = new LibraryContext();
            var books = db.Books.ToList();

            return View(books);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var book = new Book();
            return View(book);
        }

        [HttpPost]
        public ActionResult Create(Book model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new LibraryContext();
            model.CreateAt = DateTime.Now;

            if (model.BookImageFile != null)
            {
                var data = new byte[model.BookImageFile.ContentLength];
                model.BookImageFile.InputStream.Read(data, 0, model.BookImageFile.ContentLength);

                model.BookImage = new BookImage()
                {
                    Guid = Guid.NewGuid(),
                    DateChanged = DateTime.Now,
                    Data = data,
                    ContentType = model.BookImageFile.ContentType,
                    FileName = model.BookImageFile.FileName
                };
            }

            if(model.AuthorIds != null && model.AuthorIds.Any())
            {
                var author = db.Authors.Where(s => model.AuthorIds.Contains(s.Id)).ToList();
                model.Authors = author;
            }

            if (model.LanguageIds != null && model.LanguageIds.Any())
            {
                var language = db.Languages.Where(s => model.LanguageIds.Contains(s.Id)).ToList();
                model.Languages = language;
            }

            db.Books.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Books/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new LibraryContext();
            var book = db.Books.FirstOrDefault(x => x.Id == id);
            if (book == null)
                return RedirectPermanent("/Books/Index");

            db.Books.Remove(book);
            db.SaveChanges();

            return RedirectPermanent("/Books/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new LibraryContext();
            var book = db.Books.FirstOrDefault(x => x.Id == id);
            if (book == null)
                return RedirectPermanent("/Books/Index");

            return View(book);
        }

        [HttpPost]
        public ActionResult Edit(Book model)
        {
            var db = new LibraryContext();
            var book = db.Books.FirstOrDefault(x => x.Id == model.Id);
            if (book == null)
                ModelState.AddModelError("Id", "Книга не найдена");

            if(model.Key != _key)
                ModelState.AddModelError("Key", "Ключ для создания/изменения записи указан не верно");

            if (!ModelState.IsValid)
                return View(model);

            MappingBook(model, book, db);

            db.Entry(book).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Books/Index");
        }

        private void MappingBook(Book sourse, Book destination, LibraryContext db)
        {
            destination.Name = sourse.Name;
            destination.Isbn = sourse.Isbn;
            destination.Year = sourse.Year;
            destination.Cost = sourse.Cost;
            destination.GenreId = sourse.GenreId;
            destination.Genre = sourse.Genre;
            destination.CurrencyTypeId = sourse.CurrencyTypeId;
            destination.CurrencyType = sourse.CurrencyType;
            destination.IsArchive = sourse.IsArchive;
            destination.Annotation = sourse.Annotation;
            destination.Key = sourse.Key;                   //из-за Required

            if (destination.Authors != null)
                destination.Authors.Clear();

            if (sourse.AuthorIds != null && sourse.AuthorIds.Any())
                destination.Authors = db.Authors.Where(s => sourse.AuthorIds.Contains(s.Id)).ToList();


            if (destination.Languages != null)
                destination.Languages.Clear();

            if (sourse.LanguageIds != null && sourse.LanguageIds.Any())
                destination.Languages = db.Languages.Where(s => sourse.LanguageIds.Contains(s.Id)).ToList();


            if (sourse.BookImageFile != null)
            {
                var image = db.BookImages.FirstOrDefault(x => x.Id == sourse.Id);
                if (image != null)
                    db.BookImages.Remove(image);

                var data = new byte[sourse.BookImageFile.ContentLength];
                sourse.BookImageFile.InputStream.Read(data, 0, sourse.BookImageFile.ContentLength);

                destination.BookImage = new BookImage()
                {
                    Guid = Guid.NewGuid(),
                    DateChanged = DateTime.Now,
                    Data = data,
                    ContentType = sourse.BookImageFile.ContentType,
                    FileName = sourse.BookImageFile.FileName
                };
            }
        }

        [HttpGet]
        public ActionResult GetImage(int id)
        {
            var db = new LibraryContext();
            var image = db.BookImages.FirstOrDefault(x => x.Id == id);
            if (image == null)
            {
                FileStream fs = System.IO.File.OpenRead(Server.MapPath(@"~/Content/Images/not-foto.png"));
                byte[] fileData = new byte[fs.Length];
                fs.Read(fileData, 0, (int)fs.Length);
                fs.Close();

                return File(new MemoryStream(fileData), "image/jpeg");
            }

            return File(new MemoryStream(image.Data), image.ContentType);
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            var db = new LibraryContext();
            var book = db.Books.FirstOrDefault(x => x.Id == id);
            if (book == null)
                return RedirectPermanent("/Books/Index");

            return View(book);
        }



        
    }
}

RestApiClient/Controllers/ImportBooksController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using ApiBook.Api;
using RestApiClient.Models;
using RestSharp;

namespace RestApiClient.Controllers
{
    public class ImportBooksController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var logs = Import();

            return View("ImportLog", logs);
        }


        private ImportLog Import()
        {
            var startTime = DateTime.Now;

            var api = new BooksApi();
            var logs = new List<ImportItemLog>();
            var page = 1;
            //while (true)
            //{
            //    try
            //    {
                    var entity = api.BooksGet(page);
                    ApplayImport(entity, logs);
            //        page++;
            //    }
            //    catch
            //    {
            //        break;
            //    }              
            //}
            

            var successCount = logs.Count(x => x.Type == ImportItemLogType.Success);
            var failedCount = logs.Count(x => x.Type == ImportItemLogType.Error);
            var finishTime = DateTime.Now;

            var result = new ImportLog()
            {
                StartImport = startTime,
                EndImport = finishTime,
                SuccessCount = successCount,
                FailedCount = failedCount,
                Logs = logs
            };

            return result;
        }

        private List<ImportItemLog> ApplayImport(ApiBook.Model.Books entity, List<ImportItemLog> logs)
        {
            var db = new LibraryContext();

            db.Books.RemoveRange(db.Books);

            foreach(var bookDto in entity.Results)
            {
                
                var book = new Book()
                {
                    Name = bookDto.Title,
                    IsArchive = false,
                    CreateAt = DateTime.Now,
                    Key = "123456Qq",
                    Languages = GetLanguages(bookDto.Languages, db),
                    Authors = GetAuthors(bookDto.Authors, db),
                    BookImage = GetBookImage(bookDto.Id.Value, db),
                    Annotation = null,
                    Cost = null,
                    Year = null,
                    Isbn = null
                };
                db.Books.Add(book);
                db.SaveChanges();
                logs.Add(new ImportItemLog() { Message = $"Add book {book.Name}", Type = ImportItemLogType.Success});
            }
            

            return logs;
        }

        private List<Language> GetLanguages(List<string> languagesDto, LibraryContext db)
        {
            var languages = new List<Language>();

            foreach(var languageDto in languagesDto)
            {
                var language = db.Languages.FirstOrDefault(x => x.Name == languageDto);
                if(language == null)
                {
                    language = new Language()
                    {
                        Name = languageDto
                    };
                    db.Languages.Add(language);
                    db.SaveChanges();
                }

                languages.Add(language);
            }

            return languages;
        }

        private List<Author> GetAuthors(List<ApiBook.Model.Person> authorsDto, LibraryContext db)
        {
            var authors = new List<Author>();

            foreach (var authorDto in authorsDto)
            {
                var author = db.Authors.FirstOrDefault(x => x.Name == authorDto.Name && x.BirthYear == authorDto.BirthYear);
                if (author == null)
                {
                    author = new Author()
                    {
                        Name = authorDto.Name,
                        BirthYear = authorDto.BirthYear
                    };
                    db.Authors.Add(author);
                    db.SaveChanges();
                }

                authors.Add(author);
            }

            return authors;
        }
        private BookImage GetBookImage(int id, LibraryContext db)
        {
            try
            {
                var url = $"https://www.gutenberg.org/cache/epub/{id}/images/cover.jpg";
                var image = new BookImage()
                {
                    ContentType = "image/jpeg",
                    DateChanged = DateTime.Now,
                    Guid = Guid.NewGuid(),
                    FileName = "image.jpg",
                    Data = GetImage(url)
                };

                return image;
            }
            catch
            {
                return null;
            }
           
        }
        private byte[] GetImage(string url)
        {
            var client = new RestClient(url);
            var request = new RestRequest(Method.GET);
            var response = client.Execute(request);

            if (!response.IsSuccessful)
                throw new Exception("Response is not successful");

            return response.RawBytes;
        }
    }
}

RestApiClient/Views/Books/Create.cshtml
@using RestApiClient.Models
@model Book

<h3>Книга</h3>

@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.EditorForModel()
    <input type="submit" value="Сохранить" class="btn btn-primary" />
    @Html.ActionLink("Отменить", "Index", "Books", null, new { @class = "btn btn-danger" })
}

RestApiClient/Views/Books/Detail.cshtml
@using RestApiClient.Models
@model Book

<div class="container">
    <div class="row" style="align-items: center;">
        <div class="col-md-4">
            <img src="/Books/GetImage/@Model.Id" style="max-width: 300px; max-height: 600px; border: 1px solid #000000;" />
        </div>
        <div class="col-md-4">
            <p>
                <h1><u>@Model.Name</u></h1>
            </p>
            <p>
                <span><b>ISBN:</b></span>
                <span>@Model.Isbn</span>
            </p>
            <p>
                <span><b>Жанр:</b></span>
                <span>@(Model.Genre != null? Model.Genre.Name : "-")</span>
            </p>
            <p>
                @{
                    var authors = string.Join(", ", Model.Authors.Select(x => $"{x.Name}"));
                    if (string.IsNullOrEmpty(authors))
                    {
                        authors = "Нет информации";
                    }
                }

                <span><b>Авторы:</b></span>
                <span>@authors</span>
            </p>
            <p>
                <span><b>Языки:</b></span>
                <span>@string.Join(", ", Model.Languages.Select(x => $"{x.Name}"))</span>
            </p>
            <p>
                <span><b>Год издания книги:</b></span>
                <span>@Model.Year</span>
            </p>
            <p>
                <span><b>Стоимость:</b></span>
                @if (Model.Cost != null && Model.CurrencyType != null)
                {
                    <span>@($"{Model.Cost} {Model.CurrencyType.LetterCode}")<sup>1</sup></span>
                }
                else
                {
                    <span>-</span>
                }
            </p>

        </div>
    </div>
    <div class="row">
        <div class="accordion ">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-heading">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse" aria-expanded="false" aria-controls="flush-collapseOne">
                        Аннотация
                    </button>
                </h2>
                <div id="flush-collapse" class="accordion-collapse collapse show" aria-labelledby="flush-heading" >
                    <div class="accordion-body">
                        @Model.Annotation
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            @Html.ActionLink("На главную", "Index", "Books", null, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>

<hr />


<sub><i>1 - Рекомендованная розничная цена.</i></sub>

RestApiClient/Views/Books/Edit.cshtml
@using RestApiClient.Models
@model Book

<h3>Книга</h3>

@using (Html.BeginForm("Edit", "Books", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" class="btn btn-primary" />
    @Html.ActionLink("Отменить", "Index", "Books", null, new { @class = "btn btn-danger" })
}

RestApiClient/Views/Books/Index.cshtml
@using RestApiClient.Models
@model List<Book>
@{
    string controllerName = "Books";
}

<h3>Книги</h3>

@Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-primary" })
@Html.ActionLink("Импорт из API", "Index", "ImportBooks", null, new { @class = "btn btn-primary" })

<table class="table table-hover table-bordered align-middle">
    <thead>
        <tr class="align-middle">
            <th>
                Обложка
            </th>
            <th>
                Название
            </th>
            <th>
                Автор(ы)
            </th>
            <th>
                ISBN
            </th>
            <th>
                Год издания книги
            </th>
            <th>
                Дата создания записи
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var entity in Model)
        {
            <tr>
                <td>
                    <img src="/@controllerName/GetImage/@entity.Id" style="max-width: 100px; max-height: 200px;" />
                </td>
                <td>
                    <a href="/@controllerName/Detail/@entity.Id" class="text-decoration-none">@entity.Name</a>
                </td>
                <td>
                    @string.Join(", ", entity.Authors.Select(x => $"{x.Name}"))
                </td>
                <td>
                    @entity.Isbn
                </td>
                <td>
                    @entity.Year
                </td>
                <td>
                    @entity.CreateAt.ToString("dd-MM-yyyy HH:mm:ss")
                </td>
                <td class="grid-cell-action">
                    <div class="btn-group mb-3">
                        <a href="/@controllerName/Edit/@entity.Id" class="btn btn-outline-secondary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                            </svg>
                        </a>
                        <a href="/@controllerName/Delete/@entity.Id" class="btn btn-outline-secondary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"></path>
                            </svg>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>